### ISSUE TITLE
IntegrityError

### ISSUE THREAD

**Issue by rgaudin** [offspot/metrics#122]
See following logs from the hotspot demo

```
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
metrics        |     self._flush(objects)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
metrics        |     with util.safe_reraise():
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
metrics        |     raise exc_value.with_traceback(exc_tb)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
metrics        |     flush_context.execute()
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
metrics        |     rec.execute(self)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
metrics        |     util.preloaded.orm_persistence.save_obj(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
metrics        |     _emit_insert_statements(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1227, in _emit_insert_statements
metrics        |     result = connection.execute(
metrics        |              ^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
metrics        |     return meth(
metrics        |            ^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
metrics        |     return connection._execute_clauseelement(
metrics        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
metrics        |     ret = self._execute_context(
metrics        |           ^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
metrics        |     return self._exec_single_context(
metrics        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
metrics        |     self._handle_dbapi_exception(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
metrics        |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
metrics        |     self.dialect.do_execute(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
metrics        |     cursor.execute(statement, parameters)
metrics        | sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
metrics        | (sqlite3.IntegrityError) UNIQUE constraint failed: indicator_record.indicator_id, indicator_record.period_id, indicator_record.dimension_id
metrics        | [SQL: INSERT INTO indicator_record (indicator_id, value, period_id, dimension_id) VALUES (?, ?, ?, ?)]
metrics        | [parameters: (1004, 42, 1713902400, 1)]
metrics        | (Background on this error at: https://sqlalche.me/e/20/gkpj)
metrics        | [offspot_metrics::2024-04-26 07:40:50,425] INFO:Tick processing started
```

**Comment by rgaudin** [comment]
It's also hapening on check for inactivity tick

```
metrics        | [offspot_metrics::2026-03-11 13:36:00,058] INFO:Tick processing started
metrics        | [offspot_metrics::2026-03-11 13:36:00,060] INFO:Tick processing started
metrics        | [offspot_metrics::2026-03-11 13:36:00,062] WARNING:Exception occured in check for inactivity tick
metrics        | Traceback (most recent call last):
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
metrics        |     self.dialect.do_execute(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
metrics        |     cursor.execute(statement, parameters)
metrics        | sqlite3.IntegrityError: UNIQUE constraint failed: indicator_record.indicator_id, indicator_record.period_id, indicator_record.dimension_id
metrics        |
metrics        | The above exception was the direct cause of the following exception:
metrics        |
metrics        | Traceback (most recent call last):
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/main.py", line 93, in check_for_inactivity
metrics        |     self.processor.check_for_inactivity()
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/db/__init__.py", line 40, in inner
metrics        |     return func(*args, **kwargs)
metrics        |            ^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/business/processor.py", line 122, in check_for_inactivity
metrics        |     self._process_tick(now=next_tick_dt, session=session)
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/business/processor.py", line 144, in _process_tick
metrics        |     kpi_updated = self.kpi_processor.process_tick(
metrics        |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/business/kpis/processor.py", line 38, in process_tick
metrics        |     Processor.compute_kpi_values_for_aggregation_kind(
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/business/kpis/processor.py", line 104, in compute_kpi_values_for_aggregation_kind
metrics        |     values: list[Value] = Persister.get_kpi_values(
metrics        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/offspot_metrics_backend/db/persister.py", line 136, in get_kpi_values
metrics        |     for dbValue in session.execute(
metrics        |                    ^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
metrics        |     return self._execute_internal(
metrics        |            ^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2169, in _execute_internal
metrics        |     ) = compile_state_cls.orm_pre_session_exec(
metrics        |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 551, in orm_pre_session_exec
metrics        |     session._autoflush()
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3021, in _autoflush
metrics        |     raise e.with_traceback(sys.exc_info()[2])
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3010, in _autoflush
metrics        |     self.flush()
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
metrics        |     self._flush(objects)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
metrics        |     with util.safe_reraise():
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
metrics        |     raise exc_value.with_traceback(exc_tb)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
metrics        |     flush_context.execute()
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
metrics        |     rec.execute(self)
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
metrics        |     util.preloaded.orm_persistence.save_obj(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
metrics        |     _emit_insert_statements(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1227, in _emit_insert_statements
metrics        |     result = connection.execute(
metrics        |              ^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
metrics        |     return meth(
metrics        |            ^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 517, in _execute_on_connection
metrics        |     return connection._execute_clauseelement(
metrics        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
metrics        |     ret = self._execute_context(
metrics        |           ^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
metrics        |     return self._exec_single_context(
metrics        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
metrics        |     self._handle_dbapi_exception(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
metrics        |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
metrics        |     self.dialect.do_execute(
metrics        |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
metrics        |     cursor.execute(statement, parameters)
metrics        | sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
metrics        | (sqlite3.IntegrityError) UNIQUE constraint failed: indicator_record.indicator_id, indicator_record.period_id, indicator_record.dimension_id
metrics        | [SQL: INSERT INTO indicator_record (indicator_id, value, period_id, dimension_id) VALUES (?, ?, ?, ?)]
metrics        | [parameters: (1004, 60, 1773162000, 1)]
metrics        | (Background on this error at: https://sqlalche.me/e/20/gkpj)
metrics        | [offspot_metrics::2026-03-11 13:36:10,065] INFO:Tick processing started
metrics        | [offspot_metrics::2026-03-11 13:36:10,067] INFO:Tick processing started
metrics        | [offspot_metrics::2026-03-11 13:36:10,069] INFO:Tick processing started
```
